version: '3'
services:
  my-app:
    image: public.ecr.aws/e7v5r9w0/my_web_app:1.1
    ports:
      - 3000:3000
    container_name: my_web_app
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: mongodb_1
  mongo-express:
    restart: always
    image: mongo-express
    container_name: mongo-express_1
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb